# Generated by Django 6.1 on 2026-08-28 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Введите номер телефона в международном формате, например +79990000000.', regex='^\\+[1-9]\\d{7,14}$')], verbose_name='Телефон'),
        ),
    ]
